name: Product Build Workflow

on: [push, pull_request]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  VSCODE_CLI_VERSION: 1.96.4
  VSCODE_CLI_QUALITY: stable
  VSCODE_CLI_COMMIT: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
  VSCODE_CLI_UPDATE_ENDPOINT: https://update.code.visualstudio.com
  VSCODE_CLI_APPLICATION_NAME: flexpilot
  VSCODE_CLI_NAME_LONG: Flexpilot
  VSCODE_CLI_QUALITYLESS_PRODUCT_NAME: Flexpilot

jobs:
  linux_build:
    runs-on: ${{ matrix.runner }}
    name: "Build for Linux"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
            rust_target: aarch64-unknown-linux-musl
          - runner: ubuntu-24.04
            arch: x64
            rust_target: x86_64-unknown-linux-musl
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          path: 'repository'

      - name: Install Depdencies
        run: sudo apt-get update && sudo apt-get install -y musl-tools musl-dev

      - name: Add Rust Target
        run: rustup target add ${{ matrix.rust_target }}

      - name: Build CLI
        working-directory: ${{ github.workspace }}/repository/cli
        run: cargo build --release --target ${{ matrix.rust_target }}

      - name: Upload CLI Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-zip
          path: ${{ github.workspace }}/repository/cli

      - name: Upload CLI Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-cli
          path: ${{ github.workspace }}/repository/cli/target/${{ matrix.rust_target }}/release/code

      # - name: Rename CLI Binary
      #   working-directory: ${{ github.workspace }}/repository/cli
      #   run: mv ./target/release/code linux-${{ matrix.arch }}-cli

      # - name: Upload CLI Binary Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: linux-${{ matrix.arch }}-cli
      #     path: ${{ github.workspace }}/repository/cli/linux-${{ matrix.arch }}-cli


